import Head from 'next/head'
import Router, { useRouter } from 'next/router'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { Logout } from '@/Config/firebase'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const router = useRouter()

  useEffect(() => {
    
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className= {inter.className}>
        <h1>Welcome {sessionStorage.getItem('user')}</h1>

        <Link href={'page2'}>page2</Link>

        <button onClick={() => {
          sessionStorage.removeItem("Token")
          router.push('/')
          Logout()
        }}>LogOut</button>

      </main>
    </>
  )
}